language: node_js

node_js:
    - 4.0
    - 4
    - 5
    - 6
    - 7 

env:
    - HAPI_VERSION="10"
    - HAPI_VERSION="11"
    - HAPI_VERSION="12"
    - HAPI_VERSION="13"
    - HAPI_VERSION="14"
    - HAPI_VERSION="15"
    - HAPI_VERSION="16"

install:
    - npm install
    - npm install hapi@$HAPI_VERSION

sudo: false
